### ISSUE TITLE
 Error: Failed to query available provider packages

### ISSUE THREAD

**Issue by algoflows** [chronark/terraform-provider-fauna#55]
### Terraform Version
v1.2.6

### Terraform Configuration Files
![Screenshot 2022-08-02 at 22 20 31](https://user-images.githubusercontent.com/65465380/182475446-ffa7678b-6070-4990-ad3f-35e1e271a4d9.png)

### Panic Output
```
╷
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider
│ hashicorp/fuana: provider registry registry.terraform.io does
│ not have a provider named registry.terraform.io/hashicorp/fuana
│ 
│ All modules should specify their required_providers so that
│ external consumers will get the correct providers when using a
│ module. To see which modules are currently depending on
│ hashicorp/fuana, run the following command:
│     terraform providers
╵
```

### Expected Behavior
Should finish TF Init and install provider from registry

### Actual Behavior
What actually happened?

![Screenshot 2022-08-02 at 22 21 00](https://user-images.githubusercontent.com/65465380/182475509-c3894989-19ef-4bc2-9a6d-8e40df0bd1a1.png)

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform init`

### Supporting material (possible fix)

Terraform needs update, or upgrade guide wasn't followed for the provider code.

https://support.hashicorp.com/hc/en-us/articles/5511799316243-Error-Failed-to-query-available-provider-packages

**Comment by chronark** [comment]
can you double check you spelled it correctly?
```
hashicorp/fuana
```

the error message has a typo

**Comment by algoflows** [comment]
@chronark Sorry I tried quite a few ways of spelling it. nothing is working...

```
 fauna = {
      source  = "chronark/fauna"
      version = "0.5.3"
    }
```

**Comment by algoflows** [comment]
My mistake, thanks so much!

It's been a super long day 🤓
